Repository grails/grails-gsp, pull requests merged in 2024-11, with the labels that each got.

#532 Revert "Merge 6.2.x into 7.0.x"
  gradle/grails-plugin-config.gradle
  grails-plugin-gsp/build.gradle
Labels: revert

#531 Revert "Remove `-plain` suffix from plugin artifacts"
  gradle/grails-plugin-config.gradle
  grails-plugin-gsp/build.gradle
  grails-plugin-sitemesh2/build.gradle
Labels: bug, revert

#537 g:form csrf protection. Fixes #536
  grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/FormTagLib.groovy
Labels: bug

#540 Use JCL to better align with Spring and not force dependencies downstream
  LICENSE
  build.gradle
  grails-gsp/src/main/groovy/org/grails/gsp/io/DefaultGroovyPageLocator.java
  grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/GroovyPagesGrailsPlugin.groovy
  grails-plugin-gsp/src/main/groovy/org/grails/plugins/web/taglib/FormTagLib.groovy
  grails-taglib/src/main/groovy/org/grails/core/artefact/gsp/TagLibArtefactHandler.java
  grails-taglib/src/main/groovy/org/grails/taglib/encoder/WithCodecHelper.groovy
  grails-web-gsp/src/main/groovy/org/grails/web/servlet/view/GroovyPageViewResolver.java
Labels: maintenance, ci

#547 Update dependencies for `6.2.4` release
  gradle.properties
  grails-web-gsp/build.gradle
Labels: maintenance, ci, deps, bug
