Repository grails/grails-gsp, pull requests merged in 2024-09, with the labels that each got.

#477 Update Groovy and Grails dependencies
  build.gradle
  gradle.properties
Labels: maintenance, ci

#478 Update to Gradle 8.10 + Remove commonBuild
  .github/workflows/docs.yml
  .github/workflows/groovy-joint-workflow.yml
  .github/workflows/release.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  grails-gsp/src/main/groovy/org/grails/gsp/io/DefaultGroovyPageLocator.java
  grails-plugin-gsp/src/test/groovy/org/grails/gsp/jsp/SimpleJspTagTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/plugins/web/DefaultDateHelperSpec.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/pages/GroovyPageRenderingTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/AbstractGrailsTagTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/ApplyCodecTagSpec.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/FormTagLib2Tests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/FormTagLibTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/NamespacedNamedUrlMappingTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/NamespacedTagLibRenderMethodTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/RenderTagLibTests.groovy
  grails-plugin-gsp/src/test/groovy/org/grails/web/taglib/UploadFormTagTests.groovy
  grails-taglib/src/test/groovy/org/grails/taglib/GroovyPageTagWriterSpec.groovy
  grails-web-gsp/src/main/groovy/org/grails/web/gsp/GroovyPagesTemplateRenderer.java
  grails-web-jsp/src/main/groovy/org/grails/gsp/jsp/TldReader.groovy
  grails-web-jsp/src/main/groovy/org/grails/gsp/jsp/WebXmlTagLibraryReader.groovy
  grails-web-taglib/src/main/groovy/grails/artefact/gsp/TagLibraryInvoker.groovy
  grails-web-taglib/src/test/groovy/org/grails/compiler/web/taglib/TagLibraryTransformerSpec.groovy
Labels: maintenance, build

#490 Fix statements with findProperty
  build.gradle
Labels: bug

#464 docs: multi-line import example for page directive
  src/main/docs/guide/GSPBasics/pageDirectives.adoc
Labels: documentation

#497 Add asciidoctorjVersion dependency
  build.gradle
  gradle.properties
Labels: maintenance, ci
